### PR TITLE
Update email_blocks.html.twig - hackish fix, let's review! 

### PR DESCRIPTION
**Pull request by bobdenotter**

### CODE REVIEW

**Comment by I-Valchev** [comment]
@bobdenotter I thought this was fixed a couple of days ago here:

https://github.com/bolt/forms/blob/cb4e5f53c46ba052d57f5e387e4f8ea8ca71deb4/templates/email_blocks.html.twig#L56-L62

**Comment by bobdenotter** [comment]
That's a bit lower in the same file. Looks to be fixing the same problem, but I did bump into it tooday. Am too tired to see the actual cause/fix here, so i figured i'd open a hackish PR, so we at least can discuss it next week. :-)

(hackish hack seems to work on client's end, so it's not urgent)

**Comment by andysh-uk** [comment]
What was the issue? I’m happy to take a look tomorrow.

**Comment by bobdenotter** [comment]
As with all things, #42 is the answer to life, the universe and everything.

**Pull request closed without merging**
