### PR TITLE
Contenttypes as choice options

### PR DESCRIPTION
**Pull request by xiaohutai**
Some notes:
- I made a new `ContenttypeType` `FieldType`, so you need to do `type: contenttype`
- Instead of using query-builder syntax, I used the `setcontent` syntax

It should be possible to mix this behaviour with an extended `ChoiceType`, but not sure if that'd be better/worse.

Copied the ECS file from `bolt/core` repo and applied some ECS fixes.

### CODE REVIEW

**Comment by Halopend** [comment]
Have you tested this? I'm getting an error like this:

"Too few arguments to function Bolt\BoltForms\Form\ContenttypeType::__construct(), 0 passed in /home/client_palladium/palladium.xactlydesign.com/vendor/symfony/form/FormRegistry.php on line 89 and exactly 1 expected"

It appears your constructor anticipates a Bolt\Storage\Query being supplied but perhaps you intended to modify Bolt\BoltForms\FormBuilder to add it up the chain?

I really need to start using the debugger with Bolt lol.

**Comment by xiaohutai** [comment]
That should be autowired automatically. I didn't ran into that issue at all. I'm using Bolt `5.1.7` btw.

image

`

**Comment by bobdenotter** [comment]
For the record, it worked "out of the box" for me as well. 

@Halopend I'll tag a new release in a few minutes. Feel free to try again, and let us know if you're still bumping into issues! :-)

**Review by bobdenotter — COMMENTED** [review]
👍

**Comment by Halopend** [comment]
@bobdenotter @xiaohutai Nice. It's working now. Not sure if I messed something up implementing or the fresh wipe of the install base (as opposed to update) was what fixed it but it seems to work for me now.

Awesome work @xiaohutai. Super useful.

**Comment by xiaohutai** [comment]
@Halopend Awesome, great to hear!

**Pull request merged**
