### PR TITLE
Fix using custom email templates

### PR DESCRIPTION
**Pull request by Spidlace**
Hello,

Like #49 I fix custom email templates, which never took into account the custom email templates

### CODE REVIEW

**Comment by benr77** [comment]
I have just tested version v1.2.7 which has #49 merged in, and that does not fix this issue. Hopefully this one does! Thanks

**Comment by I-Valchev** [comment]
Hi @benr77 , which issue is not fixed?

I think #49 should fix it for the form template (how to display the form on the site) and this one should fix it for the email template (how the email looks after a form gets submitted).

**Comment by benr77** [comment]
Sorry I didn't see that it was two separate issues. 

My issue this morning was with the email template, so if #49 only deals with the form template then I think that's working ok, and this PR isn't merged in to v1.2.7 so that would make sense too.

**Comment by I-Valchev** [comment]
Nice! Merging this in and tagging a new release :-)

**Pull request merged**
