### PR TITLE
Add support for original symfony form events

### PR DESCRIPTION
**Pull request by denis-gorin**

### CODE REVIEW

**Comment by bobdenotter** [comment]
Hi @denis-gorin, 

Cool! I think the PR looks good as well. 

Only thing I'm kinda concerned right now is that we'd have two types of listeners. The`boltforms.post_submit` event and the ones you've added like `boltforms.pre_bind`. This might be confusing to people, since they also expect different events to be passed in: `PostSubmitEvent` vs `Symfony\Component\Form\FormEvent`

We should really have some documentation on how these work, preferably with an example of bot types. Could you draft something for that as well? 

Also, since we require php 7.2 and up now, we can use typehinting. So let's use 

```php
    public function __construct(FormEvent $event, string $formsEventName): void
``` 

instead of: 

```php
    public function __construct(FormEvent $event, $formsEventName)
```

**Comment by denis-gorin** [comment]
ok, get it

**Comment by denis-gorin** [comment]
What about the difference between `boltforms.post_submit` and  `boltforms.post_bind` ( aka `BoltFormsEvents::POST_SUBMIT` which is proxy for `FormEvents::POST_SUBMIT`)

They are the almost the same, except the order of appearance ( `boltforms.post_submit` invoked later), and the containig in it data (need to read sources):

**Example of usage:**

```php

//src\EventSubscriber\FormSubscriber.php

declare(strict_types=1);

namespace App\EventSubscriber;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Bolt\BoltForms\Event\BoltFormsEvents;
use Bolt\BoltForms\Event\BoltFormsEvent;
use Bolt\BoltForms\Event\PostSubmitEvent;

use App\AcmeBundle\Form\Recaptcha3Type;
use App\AcmeBundle\Validator\Constraints\Recaptcha3;

class FormSubscriber implements EventSubscriberInterface
{

    public function __construct()
    {
    }

    public function onFormPostSubmit(BoltFormsEvent $event): void
    {
        $postedData = $event->getEvent()->getData();
    }

    public function onPostSubmit(PostSubmitEvent $event): void
    {
        $postedData = $event->getForm()->getData()
    }

    public function onFormPreSetData(BoltFormsEvent $event)
    {
        $form = $event->getEvent()->getForm();
        $form->add('captcha', Recaptcha3Type::class, [
              'constraints' => new Recaptcha3(),
        ]);
    }

    public static function getSubscribedEvents()
    {
        return [
            'boltforms.pre_set_data' => ['onFormPreSetData', 20],
            'boltforms.post_bind'    => ['onFormPostSubmit', 20],
            'boltforms.post_submit'  => ['onPostSubmit', 20],
        ];
    }
}
```

**PS**
Should I remove the `boltforms.post_bind` event as they the same? (I just was needed `pre_set_data` event so I copy/pasted from bolt3 addon all of the events)

**Comment by bobdenotter** [comment]
Thanks, big improvement! :-)

> Should I remove the boltforms.post_bind event as they the same? 

Yes, let's do so!

**Comment by bobdenotter** [comment]
@denis-gorin Awesome! 

Let's merge this as-is. Further improvements / modifications can be done in additional PR's :-)

**Review by bobdenotter — APPROVED** [review]
👍

**Pull request merged**
